version: "2"
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/London
      - URL=steponmy.com
      - SUBDOMAINS=www,
      - VALIDATION=dns
      - DNSPLUGIN=digitalocean #optional
      - EMAIL=imax32@gmail.com #optional
      - STAGING=false #optional
    volumes:
      - ./secrets:/config/dns-conf/
      - certvolume:/config
    ports:
      - 443:443
      - 80:80 #optional
    mem_limit: 4096m
    restart: unless-stopped
  nbserver:
    #image: jupyter/minimal-notebook
    build: ./
    container_name: nbserver
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: jupyter lab --certfile=/certs/keys/letsencrypt/fullchain.pem --keyfile=/certs/keys/letsencrypt/privkey.pem
    ports:
      - 8888:8888
    volumes:
      - workvolume:/home/jovyan/work
      # - ./jupyter:/home/jovyan/.jupyter
      - certvolume:/certs
volumes:
  certvolume:
  workvolume:
